name: CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install JavaFX
      run: |
        wget https://gluonhq.com/download/javafx-17.0.1-sdk-linux -O javafx-sdk.zip
        unzip javafx-sdk.zip
        echo 'export PATH=$PATH:$PWD/javafx-sdk-17.0.1/lib' >> $GITHUB_ENV

    - name: Install Scene Builder
      run: |
        wget https://download2.gluonhq.com/scenebuilder/17.0.0/install/linux/SceneBuilder-17.0.0-SDK.zip
        unzip SceneBuilder-17.0.0-SDK.zip

    - name: Compile Java code
      run: javac --module-path $PWD/javafx-sdk-17.0.1/lib --add-modules javafx.controls,javafx.fxml Interfaces/InterfacesGraphiques/Main.java

    - name: Test with jUnit 5
      run: echo "Running jUnit 5 tests"

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to Production Server
      # Add deployment steps here, such as copying files to the server
      run: echo "Deploying to production server"
